using Cruncharr.Core.Models;
using Cruncharr.Core.Services;
using Cruncharr.Core.Utils;
using Xunit;

namespace Cruncharr.Core.Tests;

// Tests for the upstream-parity gaps closed in this change set:
// UseSonarrNumbering (filename) and SubtitleUtils (ScaledBorderAndShadow / FixCccSubtitles).
public class PortedGapTests
{
    private static EpisodeInfo MakeEpisode() => new()
    {
        Title = "The Title",
        SeriesTitle = "My Show",
        SeasonNumber = 2,
        EpisodeNumber = 5,
        Episode = "5"
    };

    [Fact]
    public void UseSonarrNumbering_OverridesEpisodeAndSeason()
    {
        var svc = new FilenameService();
        var opts = new FilenameOptions
        {
            UseSonarrNumbering = true,
            SonarrEpisode = new SonarrEpisode { SeasonNumber = 7, EpisodeNumber = 13, Title = "x" }
        };

        var name = svc.FormatFilename("S{season:00}E{episode:00}", MakeEpisode(), opts);

        Assert.Equal("S07E13", name);
    }

    [Fact]
    public void UseSonarrNumbering_Disabled_UsesCrunchyrollNumbers()
    {
        var svc = new FilenameService();
        var opts = new FilenameOptions
        {
            UseSonarrNumbering = false,
            SonarrEpisode = new SonarrEpisode { SeasonNumber = 7, EpisodeNumber = 13, Title = "x" }
        };

        var name = svc.FormatFilename("S{season:00}E{episode:00}", MakeEpisode(), opts);

        Assert.Equal("S02E05", name);
    }

    [Fact]
    public void UseSonarrNumbering_WithoutSonarrEpisode_FallsBackToCrunchyroll()
    {
        var svc = new FilenameService();
        var opts = new FilenameOptions { UseSonarrNumbering = true, SonarrEpisode = null };

        var name = svc.FormatFilename("S{season:00}E{episode:00}", MakeEpisode(), opts);

        Assert.Equal("S02E05", name);
    }

    [Fact]
    public void ScaledBorder_Yes_AddsScaledBorderLine()
    {
        var ass = "[Script Info]\r\nTitle: x\r\n\r\n[Events]\r\n";
        var result = SubtitleUtils.CleanAssAndEnsureScriptInfo(ass, false, "ScaledBorderAndShadowYes", "en-US");
        Assert.Contains("ScaledBorderAndShadow: yes", result);
    }

    [Fact]
    public void ScaledBorder_DontAdd_OmitsScaledBorderLine()
    {
        var ass = "[Script Info]\r\nTitle: x\r\n\r\n[Events]\r\n";
        var result = SubtitleUtils.CleanAssAndEnsureScriptInfo(ass, false, "DontAdd", "en-US");
        Assert.DoesNotContain("ScaledBorderAndShadow:", result);
    }

    [Fact]
    public void NormalizeScaledBorder_MapsValues()
    {
        Assert.Equal("ScaledBorderAndShadow: yes", SubtitleUtils.NormalizeScaledBorder("ScaledBorderAndShadowYes"));
        Assert.Equal("ScaledBorderAndShadow: no", SubtitleUtils.NormalizeScaledBorder("ScaledBorderAndShadowNo"));
        Assert.Null(SubtitleUtils.NormalizeScaledBorder("DontAdd"));
        Assert.Null(SubtitleUtils.NormalizeScaledBorder(""));
    }

    [Fact]
    public void FixCcc_RemovesConverterComment_WhenEnabled()
    {
        var ass = "[Script Info]\r\n; Script generated by Closed Caption Converter | www.closedcaptionconverter.com\r\nPlayDepth: 0\r\nTitle: x\r\n\r\n[Events]\r\n";
        var result = SubtitleUtils.CleanAssAndEnsureScriptInfo(ass, true, "DontAdd", "en-US");
        Assert.DoesNotContain("closedcaptionconverter.com", result);
        // CCC subs get PlayRes upserted
        Assert.Contains("PlayResX: 640", result);
    }
}
