<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <AssemblyVersion>1.0.34.0</AssemblyVersion>
    <FileVersion>1.0.34.0</FileVersion>
    <Version>1.0.34</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cruncharr.Core\Cruncharr.Core.csproj" />
  </ItemGroup>

</Project>
